# Generated by Django 3.0.8 on 2020-09-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Contador_visitas',
            field=models.IntegerField(default=0),
        ),
    ]
