# Generated by Django 3.0.8 on 2020-09-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_web', '0002_post_contador_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_preferencial',
            field=models.ImageField(upload_to='imagenes/', verbose_name='Imagen preferencial'),
        ),
    ]
