# Generated by Django 3.0.8 on 2020-09-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion_web', '0003_auto_20200928_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_preferencial',
            field=models.ImageField(max_length=255, upload_to='imagenes/', verbose_name='Imagen preferencial'),
        ),
    ]
